### ISSUE TITLE
Fine-tuning script

### ISSUE THREAD

**Issue by Davidzhangyuanhan** [facebookresearch/omnivore#15]
Hello,

Thanks for this awesome work for multi-modality pre-training!

Do you have a plan to release the fine-tuning script?

Thanks

**Comment by Davidzhangyuanhan** [comment]
In addition, what's the batch size for the Fine-tunning of image classification tasks.
Thanks!

**Comment by mannatsingh** [comment]
Hi @Davidzhangyuanhan , glad you find our work useful! 
Our plan is to release the training code, including the fine tuning script, in June!

The global batch size we used for fine tuning on image classification tasks was 512.

**Comment by Davidzhangyuanhan** [comment]
Thanks!
