### ISSUE TITLE
SUN RGB-D 19 scene classification labels

### ISSUE THREAD

**Issue by mjkleinman** [facebookresearch/omnivore#17]
Hi,

Thanks for the really cool work, and for sharing the repository! I was wondering if you can provide more details on obtaining the 19 scene classification labels for SUN RGB-D dataset. When I downloaded directly from https://rgbd.cs.princeton.edu/ (SUN RGBD V1), and I looked in the `scene.txt` file for each image, it seemed like there were more than 19 scene labels (I saw 44 different scene labels).

Thanks!

**Comment by imisra** [comment]
Hi @mjkleinman 

We use the 19 classes which are evaluated in the SUN RGB-D scene challenge (Figure 6 of https://rgbd.cs.princeton.edu/paper.pdf)


```
['bathroom', 'bedroom', 'classroom', 'computer_room',
       'conference_room', 'corridor', 'dining_area', 'dining_room',
       'discussion_area', 'furniture_store', 'home_office', 'kitchen',
       'lab', 'lecture_theatre', 'library', 'living_room', 'office',
       'rest_space', 'study_space']
```

**Comment by mjkleinman** [comment]
Thank you!

**Comment by StanLei52** [comment]
@mjkleinman @imisra I also found 44 classes as indicated by each `scene.txt`, may I know to get these 19 classes annotations?

Just filter with the given 19 classes?
