### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by AK391** [facebookresearch/omnivore#2]
have been getting urllib.error.HTTPError: HTTP Error 403: Forbidden

using     

model = torch.hub.load("facebookresearch/omnivore:main", model=model_name)

**Comment by imisra** [comment]
Hi @AK391 

What `model_name` are you using? I tried this for `omnivore_swinB`, `omnivore_swinB_imagenet21k` `omnivore_swinL_imagenet21k, and seems to work for them all

**Comment by AK391** [comment]
@imisra thanks, I was working on a space for this following the colab and getting the error https://huggingface.co/spaces/akhaliq/omnivore

using omnivore_swinB

I did not get the error when trying in colab

**Comment by imisra** [comment]
@AK391  - Working to figure this out. Seems odd that it doesn't work inside spaces.

**Comment by AK391** [comment]
@imisra thanks, might be related to this? https://github.com/pytorch/vision/issues/1876#issuecomment-764625474

**Comment by mannatsingh** [comment]
@AK391 thanks for trying to create a demo for omnivore! I think these two issues might be related. 
I tried downloading the models on different environments and from different locations including Colab and it worked everywhere. Given that the exact same setup worked with SWAG using huggingface spaces (https://github.com/facebookresearch/SWAG/pull/4), it seems likely that it is a transient S3 issue! Unless there is something wrong with the environment within spaces (unlikely).

Let's wait for a while (day or two) and then try again and see if it works?

**Comment by AK391** [comment]
@mannatsingh thanks, I tried again today, running into the same issue, will look into alternatives

**Comment by AK391** [comment]
@mannatsingh was able to resolve this

**Comment by mannatsingh** [comment]
Awesome, thanks @AK391 for figuring this out!
