### ISSUE TITLE
Get pool accuracy on epic-kitchen 100.

### ISSUE THREAD

**Issue by realgump** [facebookresearch/omnivore#20]
Dear author, 
I use the given pretrain model on the epic-kitchen dataset to inference on the validation dataset, however, I get a very poor result:
{"action_top1_acc": "35.19", "action_top5_acc": "57.09"}. Could you please tell me where I have a mistake?

**Comment by realgump** [comment]
> > Dear author, I use the given pretrain model on the epic-kitchen dataset to inference on the validation dataset, however, I get a very poor result: {"action_top1_acc": "35.19", "action_top5_acc": "57.09"}. Could you please tell me where I have a mistake?
> 
> Hi! Could you share the checkpoint with me? The download link is not available any more

Of course. However, I failed to reappear the performance in the paper. 

Please leave your email or other contact information if you need the checkpoint.

**Comment by xiaobai1217** [comment]
> > > Dear author, I use the given pretrain model on the epic-kitchen dataset to inference on the validation dataset, however, I get a very poor result: {"action_top1_acc": "35.19", "action_top5_acc": "57.09"}. Could you please tell me where I have a mistake?
> > 
> > 
> > Hi! Could you share the checkpoint with me? The download link is not available any more
> 
> Of course. However, I failed to reappear the performance in the paper.
> 
> Please leave your email or other contact information if you need the checkpoint.

My email address is y.zhang9@uva.nl

Thank you very much!!
