### ISSUE TITLE
Unable to load the model

### ISSUE THREAD

**Issue by sayakpaul** [facebookresearch/omnivore#23]
I tried running the inference notebook. It breaks at `model = torch.hub.load("facebookresearch/omnivore:main", model=model_name)` complaining:

`FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/facebookresearch_omnivore_main/hubconf.py'`

I am using Google Colab and the torch version is: `1.11.0+cu113`. I have tried with the following too but it doesn't help:

```py
model_name = "omnivore_swinB"
model = torch.hub.load("facebookresearch/omnivore", model=model_name)
```

@imisra @mannatsingh

**Comment by rohitgirdhar** [comment]
Apologies, a recent change broke hubconf. Can you please pull and try again?

**Comment by sayakpaul** [comment]
What are you suggesting to pull?

**Comment by nikhilaravi** [comment]
Or on Google colab you can add `force_reload=True` 

```
model = torch.hub.load("facebookresearch/omnivore", model=model_name, force_reload=True)
```

**Comment by sayakpaul** [comment]
https://github.com/facebookresearch/omnivore/issues/23#issuecomment-1154033827 solved the problem. Thanks!
