### ISSUE TITLE
Omnimae model release

### ISSUE THREAD

**Issue by nqx12348** [facebookresearch/omnivore#26]
Hi,

Thanks for your awesome work!

Do you have a plan to release the **Omnimae** models (https://arxiv.org/abs/2206.08356)?

Thanks!

**Comment by mannatsingh** [comment]
Hi @nqx12348 `OmniMAE` models are available at https://github.com/facebookresearch/omnivore/tree/main/omnimae :)

**Comment by nqx12348** [comment]
> Hi @nqx12348 `OmniMAE` models are available at https://github.com/facebookresearch/omnivore/tree/main/omnimae :)

Awesome! Thanks for your reply!

**Comment by mannatsingh** [comment]
Yes, we expect to release the pretraining and fine tuning code in a few weeks!
