### ISSUE TITLE
EK100 top 1 acc question

### ISSUE THREAD

**Issue by potatowarriors** [facebookresearch/omnivore#40]
your work is cool !!
I have a question while looking at the paper. There is a difference between the OMNIVORE EK100 top 1 acc in table 3 and the top 1 acc in table 6 at 47.4 vs 49.9. Are both models Swin-B models and pre-trained in the same way? Where does the 2.5% performance difference come from?

**Comment by mannatsingh** [comment]
Hi @potatowarriors the difference in performance is from the fact that for the results in Table 6 we additionally pretrain on ImageNet-21K.

**Comment by potatowarriors** [comment]
Thanks for the kind explanation, my question is solved! I'll close the issue
