### ISSUE TITLE
Tab 3 and Tab 7 NYUv2 mIoU

### ISSUE THREAD

**Issue by Zongwei97** [facebookresearch/omnivore#5]
Hello,

Thanks for the amazing work. 
I am curious about the performance differences between Tab 3 and Tab 7 on NYUv2 segmentation.

Can you confirm that the performance difference is due to the different datasets used in pre-training? 
In Tab3, is Omnivore Swin-B pre-trained on IN1K ? 
In Tab 7, is Omnivore Swin-B pre-trained on  IN21K, IN1K, K400, and SUN ? 

Thanks

**Comment by Zongwei97** [comment]
And can you clarify if you use sing-scale inference or multi-scale inference ? Thanks

**Comment by imisra** [comment]
Hi @Zongwei97 

1. Yes, the difference in performance is due to the datasets used in pretraining. You listed them out correctly.
2. We use multi-scale inference and flip. We used the code from https://github.com/hanchaoleng/ShapeConv for our evaluations.

**Comment by Zongwei97** [comment]
Thanks for your help!
